name: CD

on: workflow_dispatch

jobs:
  deploy:
    name: Publish docker image
    runs-on: ubuntu-latest
    permissions:
      packages: write
    steps:
      - uses: actions/checkout@v3
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build image
        working-directory: ./hangman-front
        run: |
          docker build -t ghcr.io/gamarr0/hangman-front:${{ github.sha }} .
      - name: Push image to registry
        run: |
          docker push ghcr.io/gamarr0/hangman-front:${{ github.sha }}
