name: CD

on: workflow_dispatch

jobs:
  deploy:
    name: Deploy image
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build image
        working-directory: ./hangman-front
        run: |
          docker build -t antonio/hangman-front:${{ git.sha }} .
      - name: Push image to registry
        run: |
          docker push ghcr.io/antonio/hangman-front:2.5
